version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '15432:5432'
    env_file:
      - .env
    restart: always

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always
    volumes:
      - ./data:/var/lib/mysql

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8084:8080'
    depends_on:
      - 'postgres'
    env_file:
      - .env
    restart: always
