version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
