version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '15432:5432'
    env_file:
      - .env
    restart: always
    volumes: 
      - ./00-postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
      - postgres-data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8084:8080'
    depends_on:
      - 'postgres'
    env_file:
      - .env
    restart: always

  server:
    image: server
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 5078:5078
    depends_on: 
      - postgres

volumes:
  postgres-data: